name: Tests

on:
  push:
    branches:
      - '*'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    runs:
      using: 'node20'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python3 -m tests